version: '3.8'

services:
  openhands:
    image: docker.all-hands.dev/all-hands-ai/openhands:latest
    container_name: openhands-gui
    ports:
      - "17243:3000"  # GUI mode on port 17243 (mapped from internal 3000)
      - "17244:17243"  # API port on 17244 (mapped from internal 17243)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../workspace:/app/workspace
      - ../config/openhands.toml:/root/.openhands/config.toml
      - ../config/github_token.txt:/root/.openhands/github_token.txt
    environment:
      - OPENHANDS_GUI_MODE=true
      - OPENHANDS_API_PORT=17244
      - OPENHANDS_WORKSPACE_PATH=/app/workspace
    networks:
      - integration-network

  # Optional: Add a service for running tests if needed
  test-runner:
    build:
      context: ../
      dockerfile: docker/Dockerfile.test-runner
    container_name: test-runner
    volumes:
      - ../workspace:/workspace
      - ../scripts:/scripts
    depends_on:
      - openhands
    networks:
      - integration-network

networks:
  integration-network:
    driver: bridge