[api]
host = "0.0.0.0"
port = 17243

[gui]
enabled = true
port = 3000

[github]
enabled = true
# Token is stored in github_token.txt

[llm]
provider = "anthropic"
model = "claude-3-7-sonnet-20250219"

[llm.providers.anthropic]
api_base = "https://api.anthropic.com/v1"
# API key is configured via GUI

[docker]
enabled = true
socket_path = "/var/run/docker.sock"

[network]
api_base = "http://localhost"

[webhooks]
github_issues = true
github_pr = true

[workspace]
path = "/app/workspace"

[integrations]
gpt_cli = true
gpt_cli_path = "/usr/local/bin/gpt"